export const dailyReports = {
  1: { patientsToday: 8, mostCommonProcedure: "Fillings", totalRevenue: 1600 },
  2: { patientsToday: 7, mostCommonProcedure: "Checkup", totalRevenue: 1400 },
  3: {
    patientsToday: 10,
    mostCommonProcedure: "Teeth Cleaning",
    totalRevenue: 2000,
  },
  4: { patientsToday: 6, mostCommonProcedure: "Fillings", totalRevenue: 1200 },
  5: { patientsToday: 8, mostCommonProcedure: "Checkup", totalRevenue: 1600 },
  6: {
    patientsToday: 12,
    mostCommonProcedure: "Teeth Cleaning",
    totalRevenue: 2400,
  },
  7: { patientsToday: 11, mostCommonProcedure: "Fillings", totalRevenue: 2200 },
  8: { patientsToday: 7, mostCommonProcedure: "Checkup", totalRevenue: 1400 },
  9: {
    patientsToday: 9,
    mostCommonProcedure: "Teeth Cleaning",
    totalRevenue: 1800,
  },
  10: { patientsToday: 5, mostCommonProcedure: "Fillings", totalRevenue: 1000 },
  11: { patientsToday: 13, mostCommonProcedure: "Checkup", totalRevenue: 2600 },
  12: {
    patientsToday: 6,
    mostCommonProcedure: "Teeth Cleaning",
    totalRevenue: 1200,
  },
  13: { patientsToday: 8, mostCommonProcedure: "Fillings", totalRevenue: 1600 },
  14: { patientsToday: 7, mostCommonProcedure: "Checkup", totalRevenue: 1400 },
  15: {
    patientsToday: 12,
    mostCommonProcedure: "Teeth Cleaning",
    totalRevenue: 2400,
  },
  16: {
    patientsToday: 11,
    mostCommonProcedure: "Fillings",
    totalRevenue: 2200,
  },
  17: { patientsToday: 9, mostCommonProcedure: "Checkup", totalRevenue: 1800 },
  18: {
    patientsToday: 6,
    mostCommonProcedure: "Teeth Cleaning",
    totalRevenue: 1200,
  },
  19: { patientsToday: 8, mostCommonProcedure: "Fillings", totalRevenue: 1600 },
  20: { patientsToday: 7, mostCommonProcedure: "Checkup", totalRevenue: 1400 },
  21: {
    patientsToday: 14,
    mostCommonProcedure: "Teeth Cleaning",
    totalRevenue: 2800,
  },
  22: { patientsToday: 5, mostCommonProcedure: "Fillings", totalRevenue: 1000 },
  23: { patientsToday: 9, mostCommonProcedure: "Checkup", totalRevenue: 1800 },
  24: {
    patientsToday: 12,
    mostCommonProcedure: "Teeth Cleaning",
    totalRevenue: 2400,
  },
  25: {
    patientsToday: 11,
    mostCommonProcedure: "Fillings",
    totalRevenue: 2200,
  },
  26: { patientsToday: 7, mostCommonProcedure: "Checkup", totalRevenue: 1400 },
  27: {
    patientsToday: 8,
    mostCommonProcedure: "Teeth Cleaning",
    totalRevenue: 1600,
  },
  28: { patientsToday: 6, mostCommonProcedure: "Fillings", totalRevenue: 1200 },
  29: { patientsToday: 14, mostCommonProcedure: "Checkup", totalRevenue: 2800 },
  30: {
    patientsToday: 5,
    mostCommonProcedure: "Teeth Cleaning",
    totalRevenue: 1000,
  },
  31: { patientsToday: 8, mostCommonProcedure: "Braces", totalRevenue: 1600 },
};
